### ISSUE TITLE
Is this a official implementacion of PatchCore?

### ISSUE THREAD

**Issue by mjack3** [amazon-research/patchcore-inspection#1]
Hello.

Is this the original Patchcore implementation or a unoffical version based on the paper?

Thanks!

**Comment by mjack3** [comment]
Hello.

Is this the original Patchcore implementation or a unoffical version based on the paper?

Thanks!

**Comment by Cveinnt** [comment]
@mjack3 hi, while I am not affiliated with amazon research, this should be the official implementation, as the paper author created this repository.

**Comment by petergehler** [comment]
Yes, this is the official implementation of the paper [Towards Total Recall in Industrial Anomaly Detection](https://arxiv.org/abs/2106.08265) Note that we also updated the arXiv version on May 5th with [new and better results](https://paperswithcode.com/sota/anomaly-detection-on-mvtec-ad) using a different backbone bringing the Detection AUROC to 99.6 and Segmentation AUROC to 98.4.
