### ISSUE TITLE
ModuleNotFoundError: No module named 'patchcore'

### ISSUE THREAD

**Issue by janamoumita1997** [amazon-research/patchcore-inspection#3]

**Comment by Cveinnt** [comment]
@janamoumita1997 this is because the `patchcore` module is located in `src/patchcore`. If you just want to run the sample training script, you can move `bin/run_patchcore.py` into the `src/`, then change the script accordingly.

**Comment by janamoumita1997** [comment]
Thanks @petergehler @Cveinnt . Both the suggestions works for me .
Thanks a lot. Closing the isssue.
