### ISSUE TITLE
No module named 'patchcore'

### ISSUE THREAD

**Issue by lyqqhgzj** [amazon-research/patchcore-inspection#33]
Hi, sir,
I run the command in sampler_training.sh, replace datapath, and get
    " No module named 'patchcore' "  file "bin/run_patchcore.py", line 12,  import patchcore.backbones
I did not change file structure. 
I try to add " sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../')) " in bin/run_patchcore.py , but get same error.
So, what should I do?

**Comment by xuewengeophysics** [comment]
Hi, sir,
In my opinion, you can try replace '../' with '../src'.

**Comment by alekseisolovev** [comment]
Try `export PYTHONPATH=src` before running.

**Comment by tuandat-github** [comment]
I run it 
![image](https://user-images.githubusercontent.com/85046877/190835888-9283cfd5-25eb-4d6a-8db4-e9dfb67584e4.png)
before . But I get " No module named 'patchcore'. 
What should I do?

**Comment by senchoi** [comment]
Hi sir,
export PYTHONPATH=src
still gives the same error in Colab.
