### ISSUE TITLE
Could anyone explain resize and imagesize ?

### ISSUE THREAD

**Issue by AlessandroPolidori** [amazon-research/patchcore-inspection#5]
Hi, can someone please explain these two parameters and, above all, why should i choose a different output size ? For instance, if my images are 480x480, what values should i choose?

**Comment by AlessandroPolidori** [comment]
@Confusezius Thank you for clearing that, but i was also interested in the reason why you would want to have a different output size (different wrt the resizing) and also why would i want to resize my images in the first place. I'm sorry if that's not really related to patchcore but i'm a novice :')

**Comment by Confusezius** [comment]
No problem :). The resizing/cropping is primarily to be in line with and comparable to previous works who used resizing/centercropping. In a practical setting, you may very well use the full input image!

**Comment by gathierry** [comment]
Hi @Confusezius could you kindly share which previous work used center cropping? I see most of them start with resizing to 256 but I've never seen one with center cropping to 224.
Thanks
