### ISSUE TITLE
(Resolved) Evaluation problem

### ISSUE THREAD

**Issue by ayuchan-22** [amazon-research/patchcore-inspection#64]
Hi, 
Thanks for sharing the code.

I have a problem running the evaluation.
I got this error:

`_pickle.UnpicklingError: invalid load key, 'v'.`

Any solution?
Thank you in advance.

**Comment by ayuchan-22** [comment]
I set `num_workers=0` and `faiss_num_workers=0` for `run_patchcore.py` and `load_and_evaluate_patchcore.py`

**Comment by Ehteshamciitwah** [comment]
Hello, I have the same problem while loading the pkl file how did you solve it? 
System: Window
Environment: python 3.9 torch 1.10

**Comment by ayuchan-22** [comment]
Set the `num_workers=0 `and `faiss_num_workers=0`

**Comment by Ehteshamciitwah** [comment]
Sorry, I did not use Git lfs during the cloning repository. If we directly download the repository, we are not able to fetch data from git lfs file. So I clone the repository using git clone and than use git lfs to fetch pre-trained weights. In this way, we can load correctly. I think there is no connection of num worker with the loading of pkl file.

**Comment by ayuchan-22** [comment]
Set the `num_workers=0` in `run_patchcore.py` and `faiss_num_workers=0` in `load_and_evaluate_patchcore.py`

**Comment by baoyuchen** [comment]
> Set the `num_workers=0` in `run_patchcore.py` and `faiss_num_workers=0` in `load_and_evaluate_patchcore.py`
Hi, I don't know why, but I'm still getting errors with this setup!

**Comment by ZiAn-Su** [comment]
> > Set the `num_workers=0` in `run_patchcore.py` and `faiss_num_workers=0` in `load_and_evaluate_patchcore.py`
> > Hi, I don't know why, but I'm still getting errors with this setup!
As @Ehteshamciitwah said, git the repository but not download. if download,files in models/ are just links. I successfully executed it.

**Comment by wahyurahmaniar** [comment]
> Sorry, I did not use Git lfs during the cloning repository. If we directly download the repository, we are not able to fetch data from git lfs file. So I clone the repository using git clone and than use git lfs to fetch pre-trained weights. In this way, we can load correctly. I think there is no connection of num worker with the loading of pkl file.

Hi, sorry, I forgot a year ago, this problem occurred when I re-trained and wanted to evaluate it, this setting worked on my PC, maybe I did other settings too but I forgot

**Comment by ayuchan-22** [comment]
> Sorry, I did not use Git lfs during the cloning repository. If we directly download the repository, we are not able to fetch data from git lfs file. So I clone the repository using git clone and than use git lfs to fetch pre-trained weights. In this way, we can load correctly. I think there is no connection of num worker with the loading of pkl file.

Hi, sorry, I think you are right, I forgot the other settings I did, it was a year ago
