### ISSUE TITLE
How/Where to visualize localized anomaly map on the test bad images.

### ISSUE THREAD

**Issue by MlLearnerAkash** [amazon-research/patchcore-inspection#8]
As discussed README.md file, the localization on the bad images. Like:

![image](https://user-images.githubusercontent.com/81233167/168235061-1ab577d2-fce6-42f4-9624-7c85208afd58.png)

My question is ****Where to look into the code and which folder it is being saved after running sample_evaluation.sh file**** (provided all the checkpoints and other parameters are taken care of)

Thnaks in advance.

**Comment by Confusezius** [comment]
You can generate sample segmentation images by just including the `--save_segmentation_images` flag, see also the respective part in the code:
https://github.com/amazon-research/patchcore-inspection/blob/b64be4734cb8295bfbadccf4f6a036b266181e57/bin/run_patchcore.py#L139-L174

Or the plot-generating function
https://github.com/amazon-research/patchcore-inspection/blob/b64be4734cb8295bfbadccf4f6a036b266181e57/src/patchcore/utils.py#L15

Hope that helps!

**Comment by MlLearnerAkash** [comment]
Thanks @Confusezius  for your generous input. Closing the issue.

**Comment by lzd-1230** [comment]
@Confusezius Hi! I've run --save_segmentation_images flag, but it provide me the seg-image combined with gt and prediction

Can I use the origin code to generate the picture like readme mentioned above? 

Or I need write another code to realize that?

![image](https://github.com/amazon-science/patchcore-inspection/assets/68856054/b51649a5-5268-4985-9411-5b09f1c08aeb)
