### ISSUE TITLE
Is it unfair to resize first and then centercrop when inferring?

### ISSUE THREAD

**Issue by yuanzhao-CVLAB** [amazon-research/patchcore-inspection#81]
Why resize at the centercrop size first, so that the pixels on the periphery of the image cannot be recognized, is this unfair? (And the length and width of the data in mvtec are the same, no need for centercrop)

**Comment by PauloFavero** [comment]
I also have this questions. In my case, I am working with high-resolution rectangular images.

I am thinking to create a tiling algorithm that will crop my image into smaller parts and feed it for feature extraction.
