### ISSUE TITLE
training with good images only

### ISSUE THREAD

**Issue by trungpham2606** [amazon-research/patchcore-inspection#9]
Thank you @petergehler for sharing the official implementation, I have a question that can we train Patchcore without the need of defect images (== training with good images only) ?

**Comment by Confusezius** [comment]
PatchCore is by default set up for the Cold-Start setting, i.e. it only uses good images in the base setup! So you should be able to use it for your problem as is :).

**Comment by trungpham2606** [comment]
Thank you @Confusezius 
I was able to train and test on my custom dataset. My dataset is pretty like the hazelnut in mvtec but the results I got is not so good. So Iam playing around with the parameters' values ^^

**Comment by Confusezius** [comment]
Sg :). If you have any more questions, feel free to continue this or open a new issue :+1: .
